---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files: null
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
    scrape_interval: 5s
  - job_name: dotnet-transitar
    static_configs:
      - targets:
          - localhost:8080
          - localhost:8081
        labels:
          group: test
      - targets:
          - api.test
          - api.test:5000
        labels:
          group: team
    metrics_path: /metrics
    scrape_interval: 5s
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
    scrape_interval: 10s
